### ISSUE TITLE
修正过滤器配置错误

### ISSUE THREAD

**Issue by MoeNek** [Skywolf-Technology/skywolf-wiki#1]
有误的链接：
https://wiki.skywolf.cloud/quickstart/player.html#%E9%85%8D%E7%BD%AEbgp%E4%BC%9A%E8%AF%9D
https://wiki.skywolf.cloud/quickstart/player.html#%E6%94%B6%E5%B0%BE

错误位置：
	ipv6 { # 指定要在该BGP邻居上跑的协议
		import import_filter_v6; # 指定导入过滤器
		export export_filter_v6; # 指定导出过滤器
		export limit 10; 
	};

应修改为：
	ipv6 { # 指定要在该BGP邻居上跑的协议
		import filter import_filter_v6; # 指定导入过滤器
		export filter export_filter_v6; # 指定导出过滤器
		export limit 10; 
	};

**Comment by pppwaw** [comment]
fixed.
